---
- name: Converge
  hosts: etcd
  module_defaults:
    get_url:
      validate_certs: false
  become: yes
  gather_facts: true
  pre_tasks:
  roles:
    - { role: andrewrothstein.etcd }
  tasks:
    - name: "Include etcd_cluster"
      include_role:
        name: "cloud_labs.etcd_cluster"
