---
- name: Converge
  hosts: etcd
  module_defaults:
    get_url:
      validate_certs: false
  become: yes
  gather_facts: false
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.etcd }
  tasks:
    - name: "Include etcd_cluster"
      ansible.builtin.include_role:
        name: "cloud_labs.etcd_cluster"
