---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - &default_platform
    name: etcd-instance-01
    hostname: etcd-instance-01
    image: mpaivabarbosa/molecule-systemd-ubuntu:20.04
    groups:
      - etcd
    command: /sbin/init
    security_opts:
      - seccomp=path/to/seccomp.json
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false
    networks:
      - name: etcd_network
  - <<: *default_platform
    name: etcd-instance-02
    hostname: etcd-instance-02
    groups:
      - etcd
  - <<: *default_platform
    name: etcd-instance-03
    hostname: etcd-instance-03
    groups:
      - etcd
provisioner:
  name: ansible
verifier:
  name: ansible
