---

- name: Check request results etcd
  block:
    - name: Send put request
      ansible.builtin.command:
        etcdctl put foo bar
      register: etcd_put_reply
      changed_when: False

    - name: Print put request reply
      ansible.builtin.debug:
        var: etcd_put_reply

    - name: Send get request
      ansible.builtin.command:
        etcdctl get foo
      register: etcd_get_reply
      changed_when: False

    - name: Print get request reply
      ansible.builtin.debug:
        var: etcd_get_reply
