---
dependency:
  name: galaxy
driver:
  name: docker
    #docker_networks:
    #- name: 'etcd_network'
    #ipam_config:
    #  - subnet: '172.18.0.0/24'
platforms:
  - name: etcd-instance-01
    hostname: etcd-instance-01 
    # custom docker images with systemd for molecule
    #   https://github.com/marciopaiva/molecule-systemd-images
    image: mpaivabarbosa/molecule-systemd-ubuntu:20.04
    groups:
      - etcd
    command: /sbin/init
    security_opts:
      - seccomp=unconfined
    # if you're using latest versions of ubuntu (22.04), check your default cgroup version.
    # command: stat -c %T -f /sys/fs/cgroup
    # if it is cgroup2fs, then change /etc/default/grub file, GRUB_CMDLINE_LINUX="systemd.unified_cgroup_hierarchy=0"
    # update grub (sudo update-grub), reboot system to eplly changes
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: false
    networks:
      - name: etcd_network
provisioner:
  name: ansible
#  # section below is used to set options in ansible.cfg
#  config_options:
#    defaults:
#      ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
