---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Include verify
      ansible.builtin.include_tasks:
        file: ../verify.yml

    - name: Include verify-no-auth
      ansible.builtin.include_tasks:
        file: ../verify-no-auth.yml
