---
- name: Converge
  hosts: etcd
  module_defaults:
    get_url:
      validate_certs: false
  become: yes
  gather_facts: false
  vars:
    # ansible-etcd-cluster-certificates role related variables
    etcd_cert_dir: /etc/ssl/private
    # ansible-etcd-cluster role related variables
    etcd_trusted_ca_file: "{{ etcd_conf_dir }}/ca.pem"
    etcd_key_file: "{{ etcd_conf_dir }}/server-key.pem"
    etcd_cert_file: "{{ etcd_conf_dir }}/server.pem"
    etcd_client_cert_auth: 'true'
    etcd_remote_cert_files:
      - "{{ etcd_cert_dir }}/ca.pem"
      - "{{ etcd_cert_dir }}/server-key.pem"
      - "{{ etcd_cert_dir }}/server.pem"
  pre_tasks:
    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - iproute2  # provides network facts
        update_cache: true
    - name: Collect facts
      ansible.builtin.setup:
  roles:
    - { role: andrewrothstein.etcd }
    - { role: andrewrothstein.cfssl }
    - { role: ansible-etcd-cluster-certificates }
  tasks:
    - name: "Include etcd_cluster"
      ansible.builtin.include_role:
        name: "cloud_labs.etcd_cluster"
