---

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    etcd_default_inventory_group: etcd
    etcd_client_port: 2379
    # ansible-etcd-cluster-certificates role related variables
    etcd_cert_dir: /etc/ssl/private
  tasks:
    - include: ../verify.yml

    - name: Try to operate storage
      block:
        - name: Generate random key
          ansible.builtin.set_fact:
            etcd_random_key: |
              {{ lookup('community.general.random_string', special=false) }}

        - name: Put value from groups[etcd_default_inventory_group][1] node
          shell: |
            echo value | \
            etcdctl --cacert={{ etcd_cert_dir }}/ca.pem \
                    --cert={{ etcd_cert_dir }}/client.pem \
                    --key={{ etcd_cert_dir }}/client-key.pem \
                    --endpoints={{ hostvars[groups[etcd_default_inventory_group][1]]['ansible_default_ipv4']['address'] }}:{{ etcd_client_port }} \
                    put key-{{ etcd_random_key }}

        - name: Get the same value from groups[etcd_default_inventory_group][2] node
          shell: |
            etcdctl --cacert={{ etcd_cert_dir }}/ca.pem \
                    --cert={{ etcd_cert_dir }}/client.pem \
                    --key={{ etcd_cert_dir }}/client-key.pem \
                    --endpoints={{ hostvars[groups[etcd_default_inventory_group][2]]['ansible_default_ipv4']['address'] }}:{{ etcd_client_port }} \
                    get key-{{ etcd_random_key }}
      delegate_to: "{{ groups[etcd_default_inventory_group][0] }}"
      when: inventory_hostname == groups[etcd_default_inventory_group][0]
